### ISSUE TITLE
How to work with external libraries?

### ISSUE THREAD

**Issue by bentxt** [sph-mn/sescript#3]
Hi
What is the recommended way when working with external js libs and when calling foreign js functions.

**Comment by sph-mn** [comment]
since the output of sescript is plain javascript code, it is as if all was only javascript. browser javascript libraries are loaded before the code compiled from sescript and can be used as usual.
nodejs' module system uses standard javascript syntax and can be used as such, but should support for the new javascript es6 module system with import/export keywords be required then there isnt direct support for that at the moment, ses-insert might help in that case.
i hope this helps.

**Comment by bentxt** [comment]
nice - ses-insert works indeed great! Can I suggest a name change to 'raw'? Just an idea...

**Comment by sph-mn** [comment]
"raw", i never thought of that. i'll consider it. an early idea was to call it "quote", like in scheme, but it wasnt used because scheme quote returns scheme data and it wouldnt be the same thing.
keywords like this cant be used as javascript function names that's why i'd add a ses- prefix.

**Comment by sph-mn** [comment]
im closing this since the original question had been answered. im still thinking about a possible name change for ses-insert.
