### ISSUE TITLE
what is the reason why the compiler separated into lang/sescript and lang/ecmascript?

### ISSUE THREAD

**Issue by bentxt** [sph-mn/sescript#4]
Could you explain a little bit more about the reasons behind structure?

**Comment by sph-mn** [comment]
in the beginnings i thought to separate the most basic ecmascript string-creation into one module. so to have a scheme interface for the most basic syntax and then just insert the values from the parsed sescript into it and thereby avoid string-append at many places. also to keep added sescript features in another module and keep lang/ecmascript more generic. now i think that the module is not very generic because it does do some extra conversions. maybe the overall code could be simplified by reducing code in lang/ecmascript and inlining it into lang/sescript.

**Comment by sph-mn** [comment]
everything has been merged into one module now.
